name: BENCHMARK

# Controls when the action will run.
on:
  push:
    branches:
     - pacino
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  hardware-ref:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Benchmarks
        run: |
          pallet=$(grep "impl pallet_" runtime/src/lib.rs | grep "Config for Runtime" | sed 's/impl pallet_//' | cut -f1 -d: | sort)
          for i in $pallet; do
            mkdir -p pallets/$i/src
            ./scripts/bench.sh -p $i -cb
          done
