name: BENCHMARK

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events for testnet
  pull_request:
    branches: [pacino]
  workflow_dispatch:

jobs:
  hardware-ref:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: |
          az container exec -g monitoring --name benchmark-node --exec-command ./bench.sh
